apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-produit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-produit
  template:
    metadata:
      labels:
        app: service-produit
    spec:
      containers:
        - name: service-produit
          image: dstndiaye/service-produit:v1
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:mem:testdb"  # Utilise H2 en mémoire
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.h2.Driver"
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.H2Dialect"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
---
apiVersion: v1
kind: Service
metadata:
  name: service-produit
spec:
  type: NodePort
  selector:
    app: service-produit
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001  # Kubernetes expose l'application sur ce port